title: CoursePlay Editor 6 for FS19
description: Managing courses in Courseplay
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
github:
  zip_url: https://github.com/CourseplayPathEditor/CoursePlay-Editor-6/raw/gh-pages/release/FS19_FarmingDesktop-1.0.0.12.zip
