title: CoursePlay Editor 6 for FS19
description: Managing courses in Courseplay
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
github:
  zip_url: http://example.com/download.zip
